export const ROUTES = {
    HOME: '/',
    APPLICATION: '/application',
    EXPERIMENT_DEPLOY: '/experiment-deploy',
    SERVICES: '/services',
    ACTIVITY_LOG: '/activity-log',
    MONITORING: '/monitoring',
    COST_CALCULATOR: '/cost-calculator',
    TEMPLATES: '/templates',
    TALK_TO_DOCUMENT: '/talk-to-document',
    TALK_TO_DATA: '/talk-to-data',
    VIEW_DATA: '/view-data',
    EXECUTE_QUERY: '/execute-query',
    UPLOAD: '/upload',
    DATA_PREPARATION: '/data-preparation',
    NOT_FOUND: '*',
  };